### PR TITLE
DDlog API update + progress encoding logical flows

### PR DESCRIPTION
**Pull request by ryzhyk**
This pull request goes together with the latest master branch of DDlog.

### CODE REVIEW

**Comment by justinpettit** [comment]
The new ddlog naming convention appears to make it so that two instances of ddlog cannot be created since the names are generic (e.g., ddlog_run() vs ovn_northd_run()).  Is that safe to assume that that won't ever be needed?

**Comment by ryzhyk** [comment]
> The new ddlog naming convention appears to make it so that two instances of ddlog cannot be created since the names are generic (e.g., ddlog_run() vs ovn_northd_run()). Is that safe to assume that that won't ever be needed?

For now, yes, we assume this is never needed.

**Comment by justinpettit** [comment]
I merged the request with a few minor changes:
    - Renamed "do_extract_lrp_networks" to "extract_lrp_networks__" as that is more standard in OVS.
    - Broke the C changes out as a separate commit from the Rust changes.

On the last point, I imagine that we're going to make a number of changes to the C-based ovn-northd code and utilities, so those will be easier to approve later as individual commits.  I imagine that the ddlog code is going to go in as one big commit, so I'm not worried about that being in fewer individual commits.  In the future, can you please break out the C changes from the ddlog ones?

Thanks!

--Justin

**Comment by ryzhyk** [comment]
Yes, that sounds like a good plan.

**Pull request closed without merging**
